spring:
  application:
    name: shf-batch-service
  profiles:
    default: "sit"
  batch:
    job.enabled: false
#    jdbc:
#      initialize-schema: always
  output.ansi.enabled: ALWAYS
server:
  port: 8081
  servlet:
    context-path: /${spring.application.name}